name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  TS_NODE_TRANSPILE_ONLY: 1
  FORCE_COLORS: 1

# todo: extract shared seto/checkout/install/compile, instead of repeat in each job.
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn compile
      - run: yarn tsc

      - run: yarn run ci

  gas-checks:
    runs-on: ubuntu-latest
    services:
      localgeth:
        image: dtr22/geth-dev

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn compile
      - run: yarn ci-gas-calc

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install

      - run: yarn compile

      - run: FORCE_COLOR=1 yarn coverage
      - uses: actions/upload-artifact@v2
        with:
          name: solidity-coverage
          path: |
            coverage/
            coverage.json

